### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by morse77** [metlar/proxy-checker#1]
Is there any easy way to add timestamp to result.txt?
Timestamp: The date and time of the last execution or result.

**Comment by metlar** [comment]
Added timestamp to result.txt

**Comment by morse77** [comment]
Thank You.

I am using it [HERE](https://www.akashtanwar.com/download/live-http-proxies-list-updated-every-5-mins/)

**Comment by morse77** [comment]
The timestamp feature added currently is not displaying properly.
Please check the output file: Attached
[demodata.txt](https://github.com/metlar/proxy-checker/files/4441237/demodata.txt)
As you can see the timestamp following the **IP:80** port is not aligned.
Can you also add a line in the top or with the date/time attached to the result file describing the time zone of the server?

**Comment by metlar** [comment]
Maybe it will help you, change the delimiter, line 31 in src/lib/Save/Txt.php
